### ISSUE TITLE
Re-export animation controls

### ISSUE THREAD

**Issue by wopian** [wobsoriano/vue-motion-one#2]
Currently only `play()` is re-exported from Motion with the intended functionality. `stop()` is technically used but its inside the `reset()` method that does a different behaviour that feels more like Motion's [`cancel()`](https://motion.dev/dom/controls#cancel) method

It would be great if we could have [`stop()`](https://motion.dev/dom/controls#stop) and [`pause()`](https://motion.dev/dom/controls#stop) available to use

**Comment by wobsoriano** [comment]
https://github.com/wobsoriano/vue-motion-one/releases/tag/v0.2.5

**Comment by wopian** [comment]
Thank you! 🎉
