### ISSUE TITLE
try to install the vue-motion-one package but the package caused a memory leak , I don't know how

### ISSUE THREAD

**Issue by jonmes** [wobsoriano/vue-motion-one#3]
![image](https://user-images.githubusercontent.com/59283322/173246331-a68b272d-4371-4cd7-af49-b55d6a899d4d.png)

**Comment by wobsoriano** [comment]
Try deleting node_modules and reinstall

**Comment by jonmes** [comment]
I tried to delete and reinstall node_modules but it won't work. also tried it on newly created vite project luckily it worked, but for some reason, it doesn't work with existing projects and vue cli projects. 
Screenshoot for cli project below
![image](https://user-images.githubusercontent.com/59283322/173301269-3329a973-ee66-4ebf-89ce-c0a565177ed3.png)
